[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#33383f"

[client]
toolbarMode = "minimal"
